package ecs

Entity :: distinct int

ECS_Error :: enum {
  NO_ERROR,
  ENTITY_DOES_NOT_HAVE_THIS_COMPONENT,
  ENTITY_DOES_NOT_MAP_TO_ANY_INDEX,
  ENTITY_ALREADY_HAS_THIS_COMPONENT,
  COMPONENT_NOT_REGISTERED,
  COMPONENT_IS_ALREADY_REGISTERED,
}